### ISSUE TITLE
[Enhancement] Healthcheck

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/container-template#10]
## Description

As a product owner, I want to present best practices for container building. One of the best practices is to use a healthcheck for containers, so the container engine can detect if the service was started sucessfully.

## Criteria

- healthcheck is provided that checks if the website is available

## Additional information

- https://www.geeksforgeeks.org/docker-healthcheck-instruction/

**Comment by daniel-schier** [comment]
there is no oci definition for healthchecks -> obsolete
