### ISSUE TITLE
[Enhancement] Release shield for stable releases only

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/container-template#12]
## Description

Currently, the release shield for docker hub shows the development releases. As a product owner, I want to promote stable releases and request to adjust the shield to show only the newest stable release versions (ex. v1.0.0).

## Criteria

- release shield shows only stable version numbers (starting with vxxx and not ending in pre-release tags) according to semver

## Additional information

- https://semver.org/

**Comment by daniel-schier** [comment]
non issue -> already implemented
