### ISSUE TITLE
[Enhancement] Security scanning of images

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/container-template#6]
## Description

Docker does provide a cli security scanning for images and we should evaluate and enable it, if feasible. Other options can be considered, too.

## Criteria

- images are scanned for security vulnerabilities
- free for opensource/public
- can be integrated in cli

## deliverables

- updated ci pipeline
- updated documentation
- issue for tooling to update the docs, if needed

## Additional information

- https://docs.docker.com/engine/scan/
- https://docs.docker.com/develop/scan-images/

**Comment by daniel-schier** [comment]
an addiiton for this story or a later one. https://snyk.io/plans/

**Comment by daniel-schier** [comment]
the whole `docker scan` thingy seems somewhat meh. you can either get 10 scans/month for free via docker hub or 200 scans/month if you have a snyk account. looking into other options like anchore.

**Comment by daniel-schier** [comment]
trivy seems to be a nice option: https://m9sweeper.io/2021/10/06/using-trivy-to-scan-docker-images-and-how-to-patch-the-vulnerabilities/
