### ISSUE TITLE
[Enhancement] website test

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/container-template#8]
## Description

As a product owner, I want to deliver high quality code and nice examples. This repository contains a website, which can and should be tested in a meaningful way. I would like to integrate a graphical website test.

## Criteria

- choose a proper tool
- update the cirrus pipeline
- the test should check for
  - links are working
  - images are loaded
  - tests should run on gekko(firefox) and webkit/chrome-based browsers

## Additional information

- selenium seems nice and easy

**Comment by daniel-schier** [comment]
obsolete
